# Generated by Django 5.1.6 on 2025-04-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
